version: '3'

services:
  heimdall:
    image: ricardbejarano/cloud-torrent:latest
    container_name: cloud-torrent
    restart: unless-stopped
    volumes:
      - ./downloads:/downloads
    ports:
      - 3000:3000

