version: '3.3'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'Europe/London'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /data/share:/mnt
        #- /mnt2:/mnt2:z
    command: '-s "Vault;/mnt;yes;no;no;USER" -u "USER;PASSWORD" -p'

networks:
  default:
