version: '3.6'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports:
            - 3333:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/containers_data/portainer/data/:/data
      - /etc/localtime:/etc/localtime:ro
# labels: # for traefik, delete this if not needed
      #traefik.enable: true
      #traefik.http.routers.portainer-http.entrypoints: web
      #traefik.http.routers.portainer.rule: Host(`portainer.czs.local`)
volumes:
  dataportainer:
